<?php 

	/*
	 * Function Name: 404 Page Settings
	 * Description: Use to modify 404 Page Template defined settings
	 * Author: AgentImage OS
	 * Author URI: http://www.agentimageos.com
	 * License: Proprietary
	 * Developer: Manuel Parejas - IM/FEWD
	 */
		

	$placeholder_val = array(
		"photo_left" => get_template_directory_uri().'/images/404-text-image.png' ,
		"photo_right" => get_template_directory_uri().'/images/404-image-right.png',
		"error_verbiage" => "Please refresh your browser. Also check the URL to make sure the address was typed correctly. If this is a new website, please allow time for your website to become active. Once the website is active, this message will be deleted.",
		"error_form" => "[contact-form-7 title='404 Page Form (Auto-generated by AIOS Initial Setup)' html_class='use-floating-validation-tip']",
		"error_template" => "sidebar"
	);

	if( !class_exists( 'aios_starter_theme_404_page_settings' ) ) {
		
		class aios_starter_theme_404_page_settings {
			
			function __construct() {

				// Add extra menu items for admins
				add_action('admin_menu', array( $this, 'register_menu') ) ;

				$this->save_error_options($_POST);
			
			}

			function register_menu(){
				add_theme_page( '404 Page Settings', '404 Page', 'manage_options', 'error-page', array($this, 'function_content') );
			}

			function function_content(){

		


				$form_val  = ( get_option('404_settings') != null ? get_option('404_settings') : $placeholder_val );



				echo '<form name="error-forms" method="post" action="?page=error-page">
						'.wp_nonce_field( 'error_fields_options', 'error_fields_content', true, true ).'
						<input type="hidden" name="error-form-flag" value="true"> 
						<div class="admin-error-page-wrap wrap">
							<div class="admin-error-page-header">
								<h1>404 Page Settings</h1>
							</div>
							<div class="admin-error-page-contents">

								<div class="admin-error-row">
									<table border="0" cellpadding="0" cellspacing="0">
										<tbody>
											<tr>
												<td>
													<strong>Left Photo</strong>
													<div class="admin-error-photo-option error-left-photo">
														'.( $form_val['photo_left']!="" ? '<img src="'.$form_val['photo_left'].'" alt="404 Page Left Photo">' : 'No Image' ).'
													</div>
													<input name="error-left-photo" type="hidden" value="'.$form_val['photo_left'].'" >
												</td>
												<td>
													<strong>Right Photo</strong>
													<div class="admin-error-photo-option error-right-photo">
														'.( $form_val['photo_right']!="" ? '<img src="'.$form_val['photo_right'].'" alt="404 Page Left Photo">' : 'No Image' ).'
													</div>
													<input name="error-right-photo" type="hidden" value="'.$form_val['photo_right'].'" >
												</td>
											</tr>
											<tr>
												<td>
													<div class="admin-error-controls error-left-photo">
														<a href="javascript:;" class="error-add-photo page-title-action" data-img="error-left-photo">Upload Photo</a><a href="javascript:;" class="error-delete-photo page-title-action" data-img="error-left-photo">Remove Photo</a>
													</div>
												</td>
												<td>
													<div class="admin-error-controls error-right-photo">
														<a href="javascript:;" class="error-add-photo page-title-action" data-img="error-right-photo">Upload Photo</a><a href="javascript:;" class="error-delete-photo page-title-action" data-img="error-right-photo">Remove Photo</a>
													</div>
												</td>
											</tr>
										</tbody>			
									</table>
								</div>

								<div class="admin-error-row">
									<strong>Verbiage:</strong>
									<textarea name="error-verbiage" >'.$form_val['error_verbiage'].'</textarea>
								</div>
								<div class="admin-error-row">
									<strong>Shortcode:</strong>
									<textarea name="error-form">'.stripcslashes($form_val['error_form']).'</textarea>
								</div>

								<div class="admin-error-row">
									<strong>Template:</strong>
									<select name="error-template">
										<option value="content-full" '.($form_val['error_template'] == "content-full" ? "selected" : '').'>Full Width</option>
										<option value="content-sidebar" '.($form_val['error_template'] == "content-sidebar" ? "selected" : '').'>with Sidebar</option>
									</select>
								</div>

								<div class="admin-main-controls">
									<input name="publish" id="publish" class="button button-primary button-large" value="Save Settings" type="submit">
								</div>

							</div>
						</div>
					</form>';

			}

			function save_error_options($post_date) {

				global $placeholder_val;
				if(get_option('404_settings') == ""){
					update_option('404_settings', $placeholder_val);
				}else {

					if(isset($_POST['error-form-flag'])) {
					
					  	if (! isset( $post_date['error_fields_content']) && wp_verify_nonce($_POST['error_fields_content'], 'error_fields_action')) {
							return;
					  	}
						
						$error_options = array(
							"photo_left" => (isset($post_date['error-left-photo']) ? sanitize_text_field($post_date['error-left-photo']) : ''),
							"photo_right" => (isset($post_date['error-right-photo']) ? sanitize_text_field($post_date['error-right-photo']) : ''),
							"error_verbiage" => (isset($post_date['error-verbiage']) ? sanitize_text_field($post_date['error-verbiage']) : ''),
							"error_form" => (isset($post_date['error-form']) ? sanitize_text_field($post_date['error-form'])  : ''),
							"error_template" => (isset($post_date['error-template']) ? sanitize_text_field($post_date['error-template'])  : '')
						);

						update_option('404_settings', (isset($error_options) ? $error_options : '') );
					}

				}

				

			}


			
			
			
		}

		new aios_starter_theme_404_page_settings;

	}



//wp_cache_delete ( 'alloptions', 'options' );
?>